### ISSUE TITLE
How to deploy with dockers in multiple server environment?

### ISSUE THREAD

**Issue by ussxyz** [giovtorres/slurm-docker-cluster#53]
How to deploy with dockers in multiple server environment? For example: 6 servers.
Since most of the time slurm will be used in multiple server environment.

Martin

**Comment by giovtorres** [comment]
You're asking to use more than 2 slurmd nodes? If so, you can just duplicate the c2 stanza in the docker-compose file and create a c3, c4, c5 and c6 nodes, which would give you 6 nodes. You'd also want to update the "c[1-2]" entries in the slurm.conf and update it to "c[1-6]" so that the config covers all the nodes.

**Comment by ussxyz** [comment]
thx man!
